---
apiVersion: v1
kind: Pod
metadata:
  name: helm
spec:
  containers:
  - name: helm
    image: "alpine/k8s:1.32.2"
    command:
      - sleep
    args:
      - "99d"
#  serviceAccountName: jenkins-robot












#apiVersion: v1
#kind: Pod
#metadata:
#  name: kaniko
#spec:
#  containers:
#  - name: kaniko
#    image: gcr.io/kaniko-project/executor:debug
#    command:
#      - sleep
#    args:
#      - "99d"
#    volumeMounts:
#      - name: kaniko-secret
#        mountPath: /kaniko/.docker
#  restartPolicy: Never
#  volumes:
#  - name: kaniko-secret
#    projected:
#      sources:
#      - secret:
#          name: dockercred
#          items:
#          - key: .dockerconfigjson
#            path: config.json
#  volumes:
#    - name: kaniko-secret
#      secret:
#        secretName: dockercred
#        items:
#          - key: .dockerconfigjson
#            path: config.json
