apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: qbec-test
spec:
  environments:
    default:
      defaultNamespace: default
      server: https://10.10.1.112:16443
  vars:
    external:
      - name: cm-value
        default: def
    computed:
      # the variable below is the configuration of the config-map data source where
      # you can specify a command, arguments to the program, environment variables,
      # and standard input
      - name: cmdConfig
        code: |
          {
            command: './config-map.sh',
            args: [ '--install', std.extVar('cm-value') ],
            env: {
              qbec_env: std.extVar('qbec.io/env'),
            },
            stdin: 'now is the time for all good men to come to the aid of the party',
          }
  dataSources:
    # data sources are declared to be of the form
    #   <kind>://<name>?configVar=<configuration-variable-name>
    # in this case kind=exec, name=config-map, and config var is cmdConfig defined above
    - exec://config-map?configVar=cmdConfig
